/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : 4th Dimension Editors
 #	author : miyako
 #	2014/09/17
 #
 # --------------------------------------------------------------------------------*/



// --- 4th Dimension Editors
void PA_OPEN_METHOD_EDITOR(sLONG_PTR *pResult, PackagePtr pParams);
